[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]

# Remappings para OpenZeppelin v√≠a npm
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]
